version: 1.0.{build}
clone_folder: c:\projects\zyan
image: Visual Studio 2017

before_build:
- choco install opencover.portable
- choco install codecov

build:
  project: source\Zyan.sln
  parallel: true
  verbosity: minimal

before_test:
- cmd: >-
    where vstest.console

    copy C:\projects\zyan\bin\UnitTests\Zyan.Communication.dll "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"

    copy C:\projects\zyan\bin\UnitTests\Zyan.Tests.dll "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"

test_script:
- OpenCover.Console.exe -register:user -target:"C:\projects\zyan\bin\UnitTests\IntegrationTest_DistributedEvents.exe" -filter:"+[Zyan*]*" -output:".\ZyanIntegrationTestCoverage.xml"
- codecov -f "ZyanIntegrationTestCoverage.xml"
- OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:"C:\projects\zyan\bin\UnitTests\Zyan.Tests.dll" -filter:"+[*]* -[MemoDb]*" -output:".\ZyanUnitTestCoverage.xml"
- codecov -f "ZyanUnitTestCoverage.xml"
